# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#- main

pool:
  vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

steps:
- script: echo k8s say Hello, world!
  displayName: 'Run a one-line script'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/azure-terraform/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'Azure-resource-jr'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'terraform-backend-jr'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacctjr'
    backendAzureRmContainerName: 'storageacctjrcontainer'
    backendAzureRmKey: 'kubernetes-dev-tfstate'
    allowTelemetryCollection: true
